
---
- hosts: ubuntu-server
  gather_facts: false
  become: true
    #become_method=sudo
    #become_user=root
    #become_ask_pass=False

    # Запрашиваем логин и пароль от удалённого хоста для подключения по SSH из зашифрованного файла vars.yaml 
  vars_files:
    - vars.yml

    # Создание пользователя 
    # Описание модуля user: https://docs.ansible.com/ansible/2.8/modules/user_module.html#user-module
  tasks: 
    - name: Add a new user named provision
      user:
        name: provision
        password: "{{ provision_password }}"
        shell: /bin/bash
        groups: sudo
        append: yes




- name: We will disable anonymous login
  ansible.builtin.lineinfile:
    path: /etc/vsftpd.conf
    regexp: '^anonymous_enable='
    line: anonymous_enable=NO

     # Разрешаем локальный вход пользователя
- name: To allow local user login
  ansible.builtin.lineinfile:
    path: /etc/vsftpd.conf
    regexp: '^#local_enable=YES'
    line: local_enable=YES

     # Разрешаем включить загрузку файлов
- name: To enable uploading file
  ansible.builtin.lineinfile:
    path: /etc/vsftpd.conf
    regexp: '^#write_enable=YES'
    line: write_enable=YES

      # Запускаем демон vsftpd
      # Описание модуля ansible.builtin.service: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/service_module.html
- name: Start vsftpd demon
  ansible.builtin.service:  
        name: vsftpd
        state: started
