
---
- hosts: ubuntu-server
  gather_facts: false
  become: true

    # Запрашиваем логин и пароль от удалённого хоста для подключения по SSH и логин пароли создаваемых пользователей из зашифрованного файла vars.yaml 
  vars_files:
    - vars.yml

    # Создание пользователeй 
    # Описание модуля user: https://docs.ansible.com/ansible/2.8/modules/user_module.html#user-module
  tasks: 
    - name: Add a new users2
      user:
        name: user2
        password: "{{ user2_password }}"
        shell: /bin/bash
        groups: sudo
        append: yes

    - name: Add a new users3
      user:
        name: user3
        password: "{{ user3_password }}"
        shell: /bin/bash
        groups: sudo
        append: yes

    - name: adding user2 to sudoers
      ansible.builtin.lineinfile: 
        path: /etc/sudoers 
        state: present
        line: 'user2 ALL=(ALL)       NOPASSWD: ALL' 
        validate: 'visudo -cf %s'

    - name: adding user3 to sudoers
      ansible.builtin.lineinfile: 
        path: /etc/sudoers 
        state: present
        line: 'user3 ALL=(ALL)       NOPASSWD: ALL' 
        validate: 'visudo -cf %s'