


     # Описание модуля ansible.builtin.shell: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
     # отключение старого файла резолва для dnsmasq
   - name: This command will disable default system dns
     ansible.builtin.shell:
       cmd: systemctl disable --now systemd-resolved

       # Описание модуля apt_repository: https://docs.ansible.com/ansible/2.8/modules/apt_repository_module.html#apt-repository-module
       # Установка dnsmasq
   - name: Update apt and install dnsmasq
     apt:
       name: dnsmasq
       state: latest

   - name: create dnsmasq.conf from template
     template:
       src: /home/mikhail/GIT_REPO/github/skillfactory/Ansible/ansible_B6.9.2/roles/dnsmasq/templates/dnsmasq.conf.j2
       dest: /etc/dnsmasq.conf
       backup: true

      # Добавление dnsmasq в автозагрузку, запуск демона
      # Описание модуля ansible.builtin.service: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/service_module.html
   - name: Run dnsmasq demon
     ansible.builtin.service:  
       name: dnsmasq
       state: started
       enabled: yes

   - name: add config file for DNS server dnsmasq
     become: yes
     template:
       src: /home/mikhail/GIT_REPO/github/skillfactory/Ansible/ansible_B6.9.2/roles/dnsmasq/templates/resolv.conf.j2
       dest: /etc/resolv.conf
     notify: restart dnsmasq

      # Настраиваем файервол для работы демона dnsmasq
      # Описание модуля community.general.ufw: https://docs.ansible.com/ansible/latest/collections/community/general/ufw_module.html
   #- name: Setting firewalld - ufw for dnsmasq at ubuntu
     #community.general.ufw:
       #rule: allow
       #name: dnsmasq
     #notify: 
     #- restart_dnsmasq
